const express = require('express')
const router = express.Router()
const authRouter = require('./auth')
const { authenticate } = require('../middleware/auth')
// const keyRouter = require('./key')
// const decryptRouter = require('./decrypt')
// const encryptRouter = require('./encrypt')
// const keyRouterAlt = require('./keygenAlt')
// const encryptRouterAlt = require('./encryptAlt')
// const decryptRouterAlt = require('./decryptAlt')
const keySymetricRouter = require('./keygenSymetric')
const encryptSymetricRouter = require('./encryptSymetric')
const decryptSymetricRouter = require('./decryptSymetric')

router.get('/welcome', (req, res) => {
    res.send('Hello World')
})

router.use('/', authRouter)
//router.use(authenticate)
//router.use('/generate', keyRouter)
//router.use('/encrypt', encryptRouter)
//router.use('/decrypt', decryptRouter)
// router.use('/generateAlt', keyRouterAlt)
// router.use('/encryptAlt', encryptRouterAlt)
// router.use('/decryptAlt', decryptRouterAlt)
router.use('/keySymetricGenerate', keySymetricRouter)
router.use('/encryptSymetric', encryptSymetricRouter)
router.use('/decryptSymetric', decryptSymetricRouter)
module.exports = router